package com.vnp.mlook.fragment;

public enum MLookAction {
	LOGIN, //
	LOGOUT, //
	FORGOTPASSWORK, MENU_HOME, MENU_LUONGTIN, MENU_MESSAGE, MENU_THONGBAO, MENU_FRIEND, MENU_PERSION, MENU_SUPPORT, MENU_LOGOUT, MENU_LOGIN, MAIN, //

}
